apiVersion: v1
kind: Namespace
metadata:
  name: dora
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dora-service
  namespace: dora
  labels:
    app: dora-service
    tags.datadoghq.com/service: dora-service
    tags.datadoghq.com/version: "1.5.2"
    tags.datadoghq.com/env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dora-service
  template:
    metadata:
      labels:
        app: dora-service
        tags.datadoghq.com/service: dora-service
        tags.datadoghq.com/version: "1.5.2"
        tags.datadoghq.com/env: prod
    spec:
      containers:
        - name: dora-service
          image: samuelblin/dora-service:1.5.2
          ports:
            - containerPort: 8080
          env:
            - name: DD_SERVICE
              value: "dora-service"
            - name: DD_VERSION
              value: "1.5.2"
            - name: DD_ENV
              value: "dev"
            - name: DD_GIT_COMMIT_SHA
              value: d153574e03866465306c3f9639d1534f7e09d91b
            - name: DD_GIT_REPOSITORY_URL
              value: https://github.com/sblin-datadog/dora-service
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: dora-service
  namespace: dora
  labels:
    app: dora-service
spec:
  selector:
    app: dora-service
  ports:
    - port: 8282
      targetPort: 8080
  type: ClusterIP

